### ISSUE TITLE
Update commonalities glossary with subproject relevant terms

### ISSUE THREAD

**Issue by shilpa-padgaonkar** [camaraproject/DeviceStatus#15]
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by NoelWirzius** [comment]
Version 0.1.0 properties
===================

Proposed alternatives follow the [guideline in commonalities](https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/API-design-guidelines.md#42-inputoutput-resource-definition) to name properties in snake_case.

Terms shared with other APIs
======================

<!DOCTYPE html>

Current term | Proposed alternatives | Comment
-- | -- | --
ueId | device_info, device, user_device, device_id | It should be added in description that it refers to client or user device, if not included in the name property. If it is an object with several details instead of a single unique ID, as it is now, maybe _id is not very accurate.
msisdn | phone_number, mobile_number | MSISDN is really restricted to mobile phone numbers, but phone number is more generic. While MSISDN is very common in Telco industry it may not be friendly to general devs
ipv4Addr | ip_v4_address | At some moment we may think in consolidating both V4 and V6 formats in one single property ip_address as version can be deducted from value
ipv6Addr | ip_v6_address |  
externalId | external_id | Description should be enhanced to inform about this option. Pending on discussions in commonalities around adoption of 3GPP GPSI
uePort | device_port, client_port | uePort used for device identification in NAT scenarios should be consolidated within device info object

<br class="Apple-interchange-newline">

<!DOCTYPE html><h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; caret-color: rgb(201, 209, 217); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">Check Device specific terms</h3>

Current term | Proposed alternatives | Comment
-- | -- | --
eventType  |  eventType  | no changes


<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px !important; caret-color: rgb(201, 209, 217); color: rgb(201, 209, 217); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;">I would like to have some internal feedback prior to take these terms to the global glossary.</p>

**Comment by rartych** [comment]
In order to integrate the common glossary in Commonalities it is needed to provide the first version of subproject relevant terms by **15th of March**.

**Comment by rartych** [comment]
I propose to wait for results of Commonalities PR:
https://github.com/camaraproject/WorkingGroups/pull/120

**Comment by shilpa-padgaonkar** [comment]
Thank you very much for the contribution to commonalities glossary. 
https://github.com/camaraproject/WorkingGroups/blob/main/Commonalities/documentation/Glossary.md
