### ISSUE TITLE
Remove 405 code in the yaml (for device-reachability-status.yaml & device-roaming-status.yaml)

### ISSUE THREAD

**Issue by bigludo7** [camaraproject/DeviceStatus#197]
**Problem description**
Following issue discussed [here](https://github.com/camaraproject/Commonalities/issues/285) in commonalities, the code 405 must not be described in the yaml; This is the case for device-reachability-status.yaml & device-roaming-status.yaml

**Expected behavior**
Remove 405 in the yaml

**Alternative solution**

**Additional context**
@hdamker @akoshunyadi @tanjadegroot -  from a release management perspective, if we update the yaml we should shift the version to `0.6.0-rc.2` - correct?

**Comment by hdamker** [comment]
> @hdamker @akoshunyadi - from a release management perspective, if we update the yaml we should shift the version to `0.6.0-rc.2` - correct?

Version numbers will only be set in release PRs, because a new release candidate has also to come with an updated CHANGELOG etc. Therefore: the first PR which is changing the YAML will set the version back to "wip", as there could be additional changes before the next release (candidate). 

There might be not enough time left before the deadline for the public release PR (August 26th) for another release candidate. So probably you will create immediately the public release PR without another pre-release in between.
