### ISSUE TITLE
Create release candidate 0.5.0

### ISSUE THREAD

**Issue by akoshunyadi** [camaraproject/DeviceStatus#82]
**Problem description**
After all necessary PRs have been merged into main, the first release candidate 0.5.0-rc should be created.

**Expected action**
- rename the version into 0.5.0-rc
- check and correct the OAS file for:
    - documentation
    - scopes
    - examples
    - in general

**Comment by hdamker** [comment]
@akoshunyadi 

To add a little bit to the expected actions - from experiences in other sub projects:

* "check and correct the OAS file" i would recommend as a PR before the release candidate gets created (without changing already to 0.5.0-rc ... otherwise there are several commits in main with this version)
* creating the release candidate itself i recommend as a PR which contains (only):
  *  update of changelog with the content of 0.5.0-rc
  *  update of README with links to the rc
  * change of version to 0.5.0-rc
* the merge commit of this "create rc PR" would be then the commit to tag as v0.5.0-rc
